import { PredictedFileOutput } from '../../src/types/predictedFileOutput';

export const data: PredictedFileOutput = {
  id: '123test',
  automated: false,
  documents: [
    {
      filename: 'automated_test_file.pdf',
      automated: false,
      classification: {
        automated: true,
        document_type: 'e-mail',
        confidence: 95,
        start_page: 0,
        end_page: 0,
      },
      header_fields: {
        email_address: {
          automated: true,
          confidence: 95,
          page: 0,
          coordinates: [0.2918, 0.1297, 0.4345, 0.1473],
          text: 'capture@parble.com',
          value: 'capture@parble.com',
        },
        email_date: {
          automated: true,
          confidence: 70,
          page: 0,
          coordinates: [0, -1, 0, -1],
          text: 'Wed, 23 Nov 2022 09:23:26 +0000',
          value: '2022-11-23',
        },
        email_receiver: {
          automated: true,
          confidence: 95,
          page: 0,
          coordinates: [0, -1, 0, -1],
          text: 'capture@parble.com',
          value: 'capture@parble.com',
        },
        email_subject: {
          automated: true,
          confidence: 100,
          coordinates: [0, -1, 0, -1],
          page: 0,
          text: '',
          value: '',
        },
      },
      tables: {},
    },
    {
      filename: 'automated_test_file.pdf',
      automated: false,
      classification: {
        automated: true,
        document_type: 'national_id',
        confidence: 94,
        start_page: 1,
        end_page: 1,
      },
      header_fields: {
        id_card_number: {
          automated: true,
          confidence: 83,
          page: 1,
          coordinates: [0.3811, 0.553, 0.5842, 0.5684],
          text: '000-0003872-89',
          value: '000000387289',
        },
        id_first_name: {
          automated: true,
          confidence: 90,
          page: 1,
          coordinates: [0.0645, 0.4054, 0.1982, 0.423],
          text: 'Specimen',
          value: 'Specimen',
        },
        id_birth_date: {
          automated: true,
          confidence: 99,
          page: 1,
          coordinates: [0.751, 0.4675, 0.8912, 0.4789],
          text: '28 02 1995',
          value: '1995-02-28',
        },
        id_nationality: {
          automated: true,
          confidence: 90,
          page: 1,
          coordinates: [0.7518, 0.4498, 0.801, 0.4601],
          text: 'D',
          value: 'DEU',
        },
        id_gender: {
          automated: true,
          confidence: 8,
          page: 1,
          coordinates: [0.4158, 0.4669, 0.4279, 0.4806],
          text: 'F',
          value: 'F',
        },
      },
      tables: {},
    },
  ],
  filename: 'automated_test_file.pdf',
  number_of_pages: 2,
  timings: {
    done: new Date(),
    upload: new Date(),
  },
};
